version: '3.3'

services:
  web_ngoldack:
    build: .
    networks:
      - proxy
    restart: always
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-ngoldack.rule=Host(`ngoldack.de`, `www.ngoldack.de`)"
        - "traefik.http.routers.web-ngoldack.entrypoints=http"
        - "traefik.http.middlewares.web-ngoldack-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.web-ngoldack.middlewares=web-ngoldack-https-redirect"
        - "traefik.http.services.web-ngoldack.loadbalancer.server.port=80"
        - "traefik.http.routers.web-ngoldack-secure.rule=Host(`ngoldack.de`, `www.ngoldack.de`)"
        - "traefik.http.routers.web-ngoldack-secure.entrypoints=https"
        - "traefik.http.routers.web-ngoldack-secure.tls.certresolver=http"
        - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
